language: elixir
sudo: false
os:
  - linux
elixir:
  - '1.6'
  - '1.7'
  - '1.8'
  - '1.9'
  - '1.10'
otp_release:
  - '19.3'
  - '20.3'
  - '21.0'
  - '22.2'
matrix:
  exclude:
    - elixir: '1.6'
      otp_release: '22.2'
    - elixir: '1.7'
      otp_release: '22.2'
    - elixir: '1.8'
      otp_release: '19.3'
    - elixir: '1.9'
      otp_release: '19.3'
    - elixir: '1.10'
      otp_release: '19.3'
    - elixir: '1.10'
      otp_release: '20.3'
script:
  - if [[ "$TRAVIS_OS_NAME" = 'windows' ]]; then ./bin/build_win32; else ./bin/build; fi
  - if [[ "$TRAVIS_ELIXIR_VERSION" = 1.10* ]]; then mix format --check-formatted; fi
notifications:
  recipients:
    - paulschoenfelder@fastmail.com
    - chris@chrishildebrand.net
